services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    secrets:
      - nginx_db_password
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password
      - mysql_backup
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - website:/var/www/html
    secrets:
      - wp_db_password
      - wp_user_password
      - wp_admin_password
    env_file:
      - .env

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: unless-stopped
    depends_on:
      - mariadb
      - wordpress
    networks:
      - inception
    volumes:
      - redis_cache:/data

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
    driver: local
    name: database
  website:
    driver: local
    name: website
  redis_cache:
    driver: local
    name: redis_cache

secrets:
  wp_db_password:
    file: ../secrets/WORDPRESS_DB_PASSWORD.txt
  wp_user_password:
    file: ../secrets/WORDPRESS_USER_PASSWORD.txt
  wp_admin_password:
    file: ../secrets/WORDPRESS_ADMIN_PASSWORD.txt
  nginx_db_password:
    file: ../secrets/DB_PASSWORD.txt
  mysql_root_password:
    file: ../secrets/MYSQL_ROOT_PASSWORD.txt
  mysql_password:
    file: ../secrets/MYSQL_PASSWORD.txt
  mysql_database:
    file: ../secrets/MYSQL_DATABASE.txt
  mysql_backup:
    file: requirements/mariadb/tools/wordpress_backup.sql