services:
  nginx:
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - "9000:9000"
    volumes:
      - website:/var/www/html
    env_file:
      - .env

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
  website:

# secrets: