services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    secrets:
      - nginx_db_password
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - website:/var/www/html
    secrets:
      - wp_db_password
      - wp_user_password
      - wp_admin_password
    env_file:
      - .env

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: unless-stopped
    depends_on:
      - mariadb
      - wordpress
    networks:
      - inception
    volumes:
      - redis_cache:/data

  ftp_serv:
    build: ./requirements/bonus/ftp
    container_name: ftp_serv
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "21:21"
      - "30000-30010:30000-30010"
    volumes:
      - website:/var/www/html
    secrets:
      - ftp_password
    env_file:
      - .env

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - "8080:8080"
    env_file:
      - .env

  static-website:
    build: ./requirements/bonus/static_website
    container_name: static_website
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - inception
    env_file:
      - .env

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
    driver: local
    name: database
  website:
    driver: local
    name: website
  redis_cache:
    driver: local
    name: redis_cache

secrets:
  wp_db_password:
    file: ../secrets/WORDPRESS_DB_PASSWORD.txt
  wp_user_password:
    file: ../secrets/WORDPRESS_USER_PASSWORD.txt
  wp_admin_password:
    file: ../secrets/WORDPRESS_ADMIN_PASSWORD.txt
  nginx_db_password:
    file: ../secrets/DB_PASSWORD.txt
  mysql_root_password:
    file: ../secrets/MYSQL_ROOT_PASSWORD.txt
  mysql_password:
    file: ../secrets/MYSQL_PASSWORD.txt
  mysql_database:
    file: ../secrets/MYSQL_DATABASE.txt
  ftp_password:
    file: ../secrets/FTP_PASSWORD.txt