services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    secrets:
      - nginx_domain
      - nginx_db_name
      - nginx_db_user
      - nginx_db_password
      - nginx_db_host
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - database:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password
      - mysql_user
      - mysql_database
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - website:/var/www/html
    secrets:
      - wp_db_name
      - wp_db_user
      - wp_db_password
      - wp_db_host
    env_file:
      - .env

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
    driver: local
    name: database
  website:
    driver: local
    name: website

secrets:
  wp_db_password:
    file: ../secrets/WORDPRESS_DB_PASSWORD.txt
  wp_db_user:
    file: ../secrets/WORDPRESS_DB_USER.txt
  wp_db_name:
    file: ../secrets/WORDPRESS_DB_NAME.txt
  wp_db_host:
    file: ../secrets/WORDPRESS_DB_HOST.txt
  nginx_db_user:
    file: ../secrets/DB_USER.txt
  nginx_db_password:
    file: ../secrets/DB_PASSWORD.txt
  nginx_db_name:
    file: ../secrets/DB_NAME.txt
  nginx_db_host:
    file: ../secrets/DB_HOST.txt
  nginx_domain:
    file: ../secrets/NGINX_DOMAIN.txt
  mysql_root_password:
    file: ../secrets/MYSQL_ROOT_PASSWORD.txt
  mysql_password:
    file: ../secrets/MYSQL_PASSWORD.txt
  mysql_user:
    file: ../secrets/MYSQL_USER.txt
  mysql_database:
    file: ../secrets/MYSQL_DATABASE.txt